# Generated by Django 5.1.1 on 2024-10-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='url_image',
            field=models.URLField(blank=True, default=True, null=True),
        ),
    ]
