# Generated by Django 5.1.1 on 2024-10-02 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_note_url_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='url_image',
            field=models.URLField(blank=True, default='No disponible', null=True),
        ),
    ]
