# Generated by Django 5.1.1 on 2024-10-03 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_alter_note_url_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fragrance',
            old_name='bran',
            new_name='brand',
        ),
        migrations.AlterField(
            model_name='fragrance',
            name='seasons_of_year',
            field=models.CharField(choices=[('S', 'summer'), ('F', 'fall'), ('W', 'winter'), ('p', 'spring')], max_length=1),
        ),
        migrations.AlterField(
            model_name='fragrance',
            name='time_of_day',
            field=models.CharField(choices=[('d', 'day'), ('n', 'night')], max_length=1),
        ),
    ]
