# Generated by Django 5.1.1 on 2024-10-03 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_rename_bran_fragrance_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fragrance',
            name='url_image',
            field=models.URLField(blank=True, default='No disponible', null=True),
        ),
    ]
