# Generated by Django 5.1.1 on 2024-10-03 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_fragrance_url_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fragrance',
            old_name='reting',
            new_name='rating',
        ),
    ]
