# Generated by Django 5.1.1 on 2024-10-03 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_rename_reting_fragrance_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fragrance',
            name='notes',
        ),
        migrations.AddField(
            model_name='fragrance',
            name='base_notes',
            field=models.ManyToManyField(related_name='note_base', to='collection.note', verbose_name='base_notes'),
        ),
        migrations.AddField(
            model_name='fragrance',
            name='middle_notes',
            field=models.ManyToManyField(related_name='note_middle', to='collection.note', verbose_name='middle_notes'),
        ),
        migrations.AddField(
            model_name='fragrance',
            name='top_notes',
            field=models.ManyToManyField(related_name='note_top', to='collection.note', verbose_name='top_notes'),
        ),
    ]
