# Generated by Django 5.1.1 on 2024-10-04 03:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0007_remove_fragrance_notes_fragrance_base_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='fragrance',
            old_name='comments',
            new_name='comment_admin',
        ),
        migrations.RemoveField(
            model_name='fragrance',
            name='rating',
        ),
        migrations.AddField(
            model_name='fragrance',
            name='rating_admin',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_user', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('comment_user', models.TextField()),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.collection')),
                ('parfum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.fragrance')),
            ],
            options={
                'unique_together': {('collection', 'parfum')},
            },
        ),
    ]
