# Generated by Django 5.1.1 on 2024-10-04 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0008_rename_comments_fragrance_comment_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fragrance',
            name='concentration',
            field=models.CharField(default='Desconocido', max_length=50),
        ),
        migrations.AlterField(
            model_name='fragrance',
            name='time_of_day',
            field=models.CharField(choices=[('d', 'day'), ('n', 'night'), ('t', 'total')], max_length=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='comment_user',
            field=models.TextField(blank=True, null=True),
        ),
    ]
